### ISSUE TITLE
Metabolism broken

### ISSUE THREAD

**Issue by mirkoloio** [Persistent-SS13/Persistent-Bay#10]
#### Description of issue
Metabolism in humans seems to be broken. Chemicals do not apply their effects to the body and stay in the body forever, not changing at all.

#### Difference between expected and actual behavior

Chemicals should apply their effects and metabolise out of the body.

#### Steps to reproduce 

Inject someone with something, monitor with a health scanner. (I.E. Spaceacilin)

#### Client version, Server revision & Game ID

Client Version: 511
Server Revision: 09e2ce70b41dc1104f8d1924e8969f41ee6aee62 - dev - 2017-12-16
Game ID: bRX-dvkD
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by FaurnsGoldberg** [comment]
fixed
