### ISSUE TITLE
Sugestion add battery to medibot and cleanbot.

### ISSUE THREAD

**Issue by JulianCarlosShirey** [Persistent-SS13/Persistent-Bay#1028]

**Comment by MrKicker** [comment]
The problem I have with this idea is that nobody would care enough to change the batteries regularly, making all the bots useless.

**Comment by JulianCarlosShirey** [comment]
could you make it so there charge with APC in the zone they are in?

**Comment by MrKicker** [comment]
I suppose so
But what gameplay value would this add?
I get that you're trying to make it realistic, but it would do nothing to affect gameplay
The minimal amount of depth doesn't seem to be worth the added complexity
