### ISSUE TITLE
Suggestion: Cleaning stuff

### ISSUE THREAD

**Issue by Tomsynth1** [Persistent-SS13/Persistent-Bay#1060]
Can someone please add a cleaning trolley ~~and some wet floor signs~~ to make cleaning better ~~and avoid annoying slips on wet floors~~. Also, consider removing cleaning bots - it would give janitors more work.

Thanks for reading!

Additionally: can there be a small cleaning office on the new map, maybe 4x4 for storage of cleaning supplies and personal lockers for cleaners

**Comment by Gr1lledcheese** [comment]
Additionally: can there be a small cleaning office, maybe 4x4 for storage of cleaning supplies and personal lockers for cleaners

**Comment by Gr1lledcheese** [comment]
Additionally: can there be a small cleaning office, maybe 4x4 for storage of cleaning supplies and personal lockers for cleaners
