### ISSUE TITLE
gas mixer / filter broken after reload

### ISSUE THREAD

**Issue by bauen1** [Persistent-SS13/Persistent-Bay#108]
#### Description of issue
Gas mixer and/or filters are broken after load
![image](https://user-images.githubusercontent.com/16723362/39063850-9d811486-44cc-11e8-9149-d8a8f0fc3d3e.png)

#### Steps to reproduce 
build a gas mixer like this:
```
 |
-*-

* = mixer
| - = pipe
```
save & load

#### Specific information for locating
NT station atmos after load on the main server

#### Length of time in which bug has been known to occur
since about forever

#### Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by ingles98** [comment]
Close this, should be dealt with (saved_vars..)
