### ISSUE TITLE
Clicking " Starting Employer" thing does nothing. Therefore you can't create a new character.

### ISSUE THREAD

**Issue by RobertRoberts2020** [Persistent-SS13/Persistent-Bay#1144]
#### Description of issue

Can't choose employer, thus can't create a new character.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: Revision Unknown
Game ID: b1r-br5h
Current map: Nexus Station

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X ] Issue could be reproduced after a restart
- [ X] Issue happened recently (less than 7 days ago)
- [ X] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Andrew-Fall** [comment]
@RobertRoberts2020 You'll have to create a starting employer via the debug menu or the verb Create Faction Beacon
