### ISSUE TITLE
Connection close after cryoing

### ISSUE THREAD

**Issue by Kei-Shin** [Persistent-SS13/Persistent-Bay#1195]
#### Description of issue
Creating a character and cryoing with said character can result in you not being able to rejoin with that character. 

#### Difference between expected and actual behavior
Expected: You hop into a cryo pod and log out. Reconnecting later you should be able to select your character and spawn in a cryo.

Actual: You hop in cryo and exit the game. Returning later any attempt of join on that same character results in the connection being closed.

#### Steps to reproduce 
1. Hop into cryo with your character.
2. Wait about 30-60 seconds (the screen was foggy at this point but was not in lobby)
3. Close the connection.
4. Reconnect later and click join game, select your character.
5. "Connection Closed"

#### Specific information for locating
The only information that is given to the user is "Connection closed". There could be a runtime or error associated in the logs but the end user is not given this info. My guess is its a result of not waiting to be presented the lobby screen. That is my guess at least.

#### Length of time in which bug has been known to occur
At the release of The Nexus(10am) - 10pm(Server closing in under an hour)

#### Client version, Server revision & Game ID
Client Version: 512
Server Revision: 15ef3fa72fe8eac6fe9882fe9cb4eae64d311787 - dev - 2019-06-24
Game ID: b1U-alOk
Current map: Nexus Station

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players (Not known if this has happened to other players)
- [x] Issue could be reproduced after a restart (Server restarted 45 minute ago from this post and the issue _ahem persists._ 
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Kei-Shin** [comment]
Its plenty of users have reported seeing this issue. I am not sure if this is a result of the data not saving or what. I also created a second character to test a different issue and found that he also experiences the same problem, however, "The sudden appearance of gravity makes you fall to the floor!" does get printed before connection closes this time around.

**Comment by michaelchessall** [comment]
surely this is fixed
