### ISSUE TITLE
Recycler icon doesn't rotate correctly

### ISSUE THREAD

**Issue by VNLoverMay** [Persistent-SS13/Persistent-Bay#1196]
#### Description of issue
When rotating the recycler, the input and output reorient correctly but the icon does not.

#### Difference between expected and actual behavior
The icon should reflect where the input/output are.

#### Steps to reproduce 
Attempt to rotate a recycler.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by PsyCommando** [comment]
There's no sprites for any other directions.
