### ISSUE TITLE
Stacking ores doesn't increase the size of the stack

### ISSUE THREAD

**Issue by tacct6** [Persistent-SS13/Persistent-Bay#1199]
#### Description of issue
When stacking ores, the stack will always stay at the smallest stack size (tiny item)

#### Difference between expected and actual behavior
I'd expect stacking ores to scale it's size similar to how stacking sheets work.

#### Steps to reproduce 
1. Grab two separate stacks of ore (probably from the asteroid)
2. Combine said ores
3. Realize how you can now stack insane amounts of ores in any container

#### Specific information for locating

https://github.com/Persistent-SS13/Persistent-Bay/blob/989cb8a326befca0b5a5d3977e23dbf64519ed36/code/modules/materials/materials_ore.dm

#### Length of time in which bug has been known to occur
discovered today, I assume it's been around when stackable ores were added

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 91ed0b92c82b3f665641ca4509aba1f4932cd2a3 - dev - 2019-06-24
Game ID: b1U-cJfv

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Andrew-Fall** [comment]
This isn't actually a bug. Given enough ore in one stack the size will increase, however it is a small increase and should probably be a larger increase.
