### ISSUE TITLE
Refined materials can't be put in the mineral processor

### ISSUE THREAD

**Issue by tacct6** [Persistent-SS13/Persistent-Bay#1211]
#### Description of issue

You aren't able to put materials like steel, or refined materials like iron ingots in the mineral processor, which is how it used to work, this makes advanced alloys like plasteel and OCP currently unobtainable for the most part.

#### Difference between expected and actual behavior
expected: the mineral processor should accept refined materials like steel and plasteel since advanced alloys require those as ingredients
actual: none of these materials are accepted by the mineral processor 

#### Steps to reproduce 
1. attempt to make plasteel by alloying steel and platinum
2. realize the mineral processor doesn't accept steel when put on the input

#### Specific information for locating

alloy recipes: https://github.com/Persistent-SS13/Persistent-Bay/blob/3d3d68bb89b750543200e0addd453dc477268e3c/code/modules/materials/definitions/materials_metal.dm#L313

mineral processor: https://github.com/Persistent-SS13/Persistent-Bay/blob/3d3d68bb89b750543200e0addd453dc477268e3c/code/modules/mining/machinery/mineral_processor.dm
#### Length of time in which bug has been known to occur

sometime between last map and the current map

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 658b65a3f667537961b70ee67b1f02624e3f8d52 - dev - 2019-06-26
Game ID: b1W-bpLm

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Andrew-Fall** [comment]
Refined metals should not be inserted into the refinery as of our current setup. The requirements for plasteel were incorrectly setup, but have since been fixed.
