### ISSUE TITLE
Businesses cannot be closed

### ISSUE THREAD

**Issue by Andrew-Fall** [Persistent-SS13/Persistent-Bay#1229]
https://cdn.discordapp.com/attachments/592766002232557627/594341685002240000/unknown.png

**Comment by PsyCommando** [comment]
Uh, we'll need more details on this one. I tried it on my own business and it works fine.

**Comment by XanderDox** [comment]
@PsyCommando Closed business. People were still clocking in AND getting paid, as per transaction records and personal testimony.
