### ISSUE TITLE
Plate Carriers have icon issues.

### ISSUE THREAD

**Issue by Andrew-Fall** [Persistent-SS13/Persistent-Bay#1231]
https://cdn.discordapp.com/attachments/592766002232557627/594353840548085760/unknown.png
https://cdn.discordapp.com/attachments/592766002232557627/594353872454287362/unknown.png

**Comment by PsyCommando** [comment]
Its not exactly an issue. Its just the way accessories are handled that does this.. Basically, nobody defined a way to just not draw accessories when they really shouldn't show anything on the sprite of the parent clothing. So what they did was just let the thing "error" out cause it would still look like nothing was drawn. The nice way of fixing it would be to set blank sprites for all invisible accessories states, like armor plates in that case. I managed to force the onmobs ones to a blank icon state, but the one on the actual inventory were posing some problems. 
So I took the easy way out and removed the default error icon state. That should fix it in a simple way, considering its an issue with how clothing works in the first place...
