### ISSUE TITLE
Material Rod Dupe

### ISSUE THREAD

**Issue by Andrew-Fall** [Persistent-SS13/Persistent-Bay#1232]
Material Rods (aka steel rods for grills) can be used to produce infinite steel via inserting them into a fabricator as each one gives one sheet worth of steel, which can be converted into two steel bars. This issues arises from material stacks having a separate var from materials (datum) that dictate how much material an object should have. (Something like perobj)

**Comment by PsyCommando** [comment]
Using the material entry would produce bad results.

Stacks recalculates their matter var content each times something is added or removed. I wrote that a while ago to make things a whole lot simpler and less crashy. Especially when dealing with any machines using the matter var of an item to get material from it. My guess is changing the rods to use material stacks might have bypassed some of the update procs for the matter content or it tries to use the material's entry directly and forget that its a rod and not a sheet..
