### ISSUE TITLE
Dysfunctional Cooking

### ISSUE THREAD

**Issue by Tomsynth1** [Persistent-SS13/Persistent-Bay#1237]
#### Description of issue
1. There doesn't seem to be a way to obtain tomatoes or eggs (edit: I just learned about cryo crates, please disregard the egg complaint), which are both very useful in cooking. I would suggest making eggs a product of the bio generator or somehow implementing a way to obtain chickens.
 
2. The screenshots below seem to suggest that it is not possible to create cheese wheels or dough, although I have not been able to attempt to make these due to lack of ingredients.

#### Specific information for locating

![Dough](https://user-images.githubusercontent.com/45194738/60380079-889e1c00-9a82-11e9-8a36-db688d1fdf74.JPG)
![Cheese wheel](https://user-images.githubusercontent.com/45194738/60380082-8cca3980-9a82-11e9-81a7-402f5a55b5af.JPG)

**Comment by PsyCommando** [comment]
You can create both of those. They don't create a reagent so their result var is null, but they both define a proc on reaction that creates the physical items for the cheese wheel and dough. You probably should have tried this before reporting?
