### ISSUE TITLE
Accessories on Plate Carriers duplicate

### ISSUE THREAD

**Issue by 2cwldys** [Persistent-SS13/Persistent-Bay#1241]
I examine myself and it shows the following accessories added to my plate carrier but doubles or triples I think every time I enter or exit cryo.

I take off the accessory, drop it, and click on my plate carrier anywhere else, the item returns to my palm, and the pouch inventory opens. It is also openable wherever someone may find the pouch on the ground, and can drag it to themselves and remove whichever inventory item was in it.

**Comment by 2cwldys** [comment]
![image](https://cdn.discordapp.com/attachments/509902632614101014/594671301034115072/unknown.png)
![image](https://user-images.githubusercontent.com/13092937/60390431-8a78d700-9aa4-11e9-9635-dd59c50799e9.png)

**Comment by michaelchessall** [comment]
this issue really was urgent,
