### ISSUE TITLE
Suggestion: Bag of Holding to Retail Fabricators

### ISSUE THREAD

**Issue by 2cwldys** [Persistent-SS13/Persistent-Bay#1242]
I bring forth a suggestion today, regarding adding the beloved science Bag of Holding to the Retail Fabricators, they should be REALLY hard to produce and probably require rare materials.

**Comment by PsyCommando** [comment]
Honestly, it was nerfed so much last round that it wasn't all that beloved anymore. Except for people that wanted to carry like 50 pistols and smgs. Because the weight class restriction was set to only small items.

**Comment by 2cwldys** [comment]
Oh haha, didn't know that. I loved that bugger. Thanks!
