### ISSUE TITLE
Suggestion: Allow fabricators to take common trash

### ISSUE THREAD

**Issue by 2cwldys** [Persistent-SS13/Persistent-Bay#1243]
It would be interesting for culinary practices and businesses to stuff the general fabricators or any fabricator with the plates from eaten food, and a way to recycle junk back into common material within the economy with it's physical goods. This is a suggestion, to whereas a normal recycling facility may be preferred, but this would assist in removing clutter in common businesses. Allowing for certain health standards by government of businesses to be created like how culinary businesses are truly rated in reality.

**Comment by PsyCommando** [comment]
The recycler does that already. And people are already setting up garbage collection on lower levels.

**Comment by 2cwldys** [comment]
Neat!
