### ISSUE TITLE
Cannot view IDs inside of PDAs

### ISSUE THREAD

**Issue by 2cwldys** [Persistent-SS13/Persistent-Bay#1258]
![image](https://user-images.githubusercontent.com/13092937/60469951-7b249580-9c2c-11e9-985a-44c12bffcf13.png)

[Look at ID]

Shows virtually nothing! :P

**Comment by Tomsynth1** [comment]
I also get this issue.

**Comment by fernandos13** [comment]
same here
edit; not in wallets either
