### ISSUE TITLE
Vents and Scrubbers a do not sync with air alarms

### ISSUE THREAD

**Issue by iampamp** [Persistent-SS13/Persistent-Bay#13]
#### Description of issue
Air vents and scrubbers do not properly connect to air alarms when being installed, this makes setting up atmospheric networks nearly useless when creating new rooms.

#### Difference between expected and actual behavior
Expected: After wrenching down a vent/scrubber in a room, I would be able to turn on and configure the vent settings via Air alarms.

Actual: After Wrenching down a vent/scrubber, there is no list of the new vents on air alarms, making it impossible to fill rooms full of air via vents.

#### Steps to reproduce 
1. Create a new room
2. Define the new room with blueprints
3. Create an APC &  Air Alarm for said room (The name of the Air Alarm & APC will change to the room name (whatever you put in step 2)
4. Place a uvent fitting (Vent) and/or scrubber fitting in your newly created room
5. Be disappointed when said vents and scrubbers do not appear on the Air Alarm you placed in the room.

#### Specific information for locating
"uvent fitting" and "scrubber fitting" from the pipe dispenser machine.

#### Length of time in which bug has been known to occur
Unknown/since the start of the new player-built map

#### Client version, Server revision & Game ID
Client Version: 511
Server Revision: 504a2b95fa730b5bae1a4f5b9c5cb3a430afd22f - dev - 2017-12-26
Game ID: bR8-c4ax

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players (
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this

#### NOTES:
[Vakoth had this issue on another server and mentioned they were able to fix it like this](https://image.prntscr.com/image/UxWkgvWCR2avBIGSeFmamA.png)

After server restarts, the issue seems to fix itself

**Comment by SirBloodBuske** [comment]
Did you activate the vents with your multitool?

**Comment by FaurnsGoldberg** [comment]
fixed
