### ISSUE TITLE
Prosthetic Organ Fabricator counting negative

### ISSUE THREAD

**Issue by 2cwldys** [Persistent-SS13/Persistent-Bay#1370]
When I try to use the prosthetic organ fab, it has about a 10 second production time, then continues to count negative.

Example Given:
-210 seconds

Dissassembly and cancel button doesn't help and a patient has died so far cause of not being able to print them organs.

**Comment by PsyCommando** [comment]
Yeah, that was my bad, I had commented out the Process() proc on the organ printer for some reasons
