### ISSUE TITLE
Dragging and grabbing bodies into/onto machines should be consistent.

### ISSUE THREAD

**Issue by robbym** [Persistent-SS13/Persistent-Bay#146]
Many machines in medical are inconsistent.
Some you drag someone to, others can grab and click the machine, and some you can do both.

Specifics:
- **neural lace resleever**
  - Doesn't remove the grab icon when you place someone in it and should also allow drag.
  - Doesn't have an eject verb.
  - Grab has a timer.
- **Body Scanner** (_inconsistent case_)
  - Grab click is instantaneous while drag has a timer.
  - Has both enter and ejects verbs.
- **sleeper**
  - Doesn't have a grab click.
  - Doesn't have an eject verb.
- **roller bed**
  - Has both grab and drag.
  - Grab has a timer while drag is instantaneous.
  - Pulling and pushing a roller bed with someone on it has a tendency to leave the body behind, floating, as if they were still on the bed.
  - Dragging someone onto an operating table whilst they are on a roller bed does not dissociate the person from the bed, so if you are pulling a roller bed with someone on it, then drag them onto the operating table, then move the roller bed, then they will teleport back onto the bed.
- **Operating Table** (_inconsistent case_)
  - Both grab and drag are instantaneous.
  - As mentioned above, has weird interactions with roller beds.

**Comment by robbym** [comment]
Suggested fixes:
- **neural lace resleever**
  - Add drag functionality.
  - Remove grab status when placed in machine.
- **Body Scanner**
  - Add timer to grab click (make both call same function)
- **sleeper**
  - Add grab click functionality
- **roller bed**
  - Fix janky floating bug.
- **Operating Table**
  - Add timers to both grab and drag.

**Comment by Zero-Bits** [comment]
This has been resolved. Please mark it as such.
