### ISSUE TITLE
Autolathes don't work properly

### ISSUE THREAD

**Issue by ourpar** [Persistent-SS13/Persistent-Bay#224]
#### Description of issue
1. Upon clicking on an autolathe for the first time, the UI opens like normal, however, any future attempt of opening the UI afterwards results in nothing happening (incase you ask: no, I didn't have the menu minimized or hidden anywhere). Reconstructing/hacking any wire seems to (inconsistently) refresh the autolathe in some way, temporarily allowing access to the UI.
2. Putting materials inside the autolathe (tested with glass, steel, and platinum sheets) results in nothing happening. 
3. When I was able to see the autolathe UI (using the workaround on the first bullet), random items were able to be printed for free, and there were a bunch of items from the R&D Protolathe/circuit imprinter listed as printable objects.

#### Steps to reproduce 
 * 1: Build/Find an autolathe
 * 2: Try to access the autolathe UI by clicking on it
   * 2.1: If the UI has appeared, close out of it.
   * 2.2: Try to open the UI a second time.
 * 3: Be disappointed when the UI does not open.

#### Length of time in which bug has been known to occur
It started since the server was put back up on 17.May.2018 (Seems like https://github.com/Persistent-SS13/Persistent-Bay/pull/208 is the most recent PR that changed autolathes)

#### Client version, Server revision & Game ID
Server Revision: 82c8b1e8f9cbcaf5285765310876bb78f894115c - dev - 2018-05-17
Game ID: bUp-dqNq

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once ( *Tested on two separate autolathes many times* )
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Zero-Bits** [comment]
Anyone else having this issue? Any additional information available on it?

**Comment by ourpar** [comment]
I've noticed people talking about it ingame once or twice, and electric mentioned the bug on the discord now too. It seems he discovered that all existing autolathes actually function as intended (besides the fact that some items can be printed for free), but attempting to load any sort of materials (including things like flashlights) into the autolathe is what triggers it to break, newly constructed autolathes seem to be the ones that stop working after 2 UI clicks.

**Comment by ourpar** [comment]
Closing since there was a new autolathe rework and I'm guessing this specific one won't be added back
