### ISSUE TITLE
[BUG] Cannot clamp bleeding if wounds have not healed from previous surgery

### ISSUE THREAD

**Issue by Elianabeth** [Persistent-SS13/Persistent-Bay#231]
#### Description of issue
Cannot use a hemostat to clamp bleeding if you've previously opened the surgical area

#### Difference between expected and actual behavior
Expected: Hemostat will allowing you to clamp bleeding
Actual: No notice of anything wrong, treated as though clamping had already been done when attempting to clamp, but wound will keep bleeding.

#### Steps to reproduce 
Preform surgery on a body, anywhere.
Preform the surgical steps in the order of: 
Scalpel -> Hemostat -> Cautery -> Scalpel -> Attempt to Hemostat again

#### Specific information for locating

https://github.com/Persistent-SS13/Persistent-Bay/blob/5f88f7ba7839383c3cd849182fece2683ae5ff29/code/modules/organs/external/_external.dm#L676-L705
In the updated_damages() the current clamped flag is carried over for a wound. During surgery, when you cauterize a wound, it doesn't 'fully' heal it - thus it is still counted as a wound and the clamped flag will still remain. 

I recommend fixing this through allowing cauterization to call a 'unclamp' function from _external, in addition to the close() function already called.
https://github.com/Persistent-SS13/Persistent-Bay/blob/5f88f7ba7839383c3cd849182fece2683ae5ff29/code/modules/surgery/generic.dm#L279-L287

#### Length of time in which bug has been known to occur

Since Baystation port

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]

**Comment by Zero-Bits** [comment]
Solved by #242
