### ISSUE TITLE
Solar control console does not sync with every solar panel

### ISSUE THREAD

**Issue by XElectricX** [Persistent-SS13/Persistent-Bay#235]
Every time the server loads, only 40 of my 96 solar panels are detected by the solar control console when I resync them.
![image](https://user-images.githubusercontent.com/30136710/40568155-00c4daf6-6047-11e8-8142-aa211ee4fd97.png)
_Before._

Cutting the wires and then reattaching them (circled in red) forces the solar control console to recognize them.
![image](https://user-images.githubusercontent.com/30136710/40568226-55bceb3e-6047-11e8-9fc1-95107ac35f5c.png)
_After._

For reference, this is how my solar array is set up.
![image](https://user-images.githubusercontent.com/30136710/40568323-e9570686-6047-11e8-9a9e-186176888c1f.png)

**Note:** The terminal above the wires (where the red circle is) is bugged. It used to be connected to the PSU, but we tried removing it long ago and it was not possible. The terminal below the PSU is the one used.

**Comment by Zero-Bits** [comment]
Strange. Anyone know what could be causing this, codewise?

**Comment by Zero-Bits** [comment]
It could be that the network is constructed before all the cables are loaded in. But that's just an educated guess.

**Comment by PrPleGoo** [comment]
Could you do varedits to check which solar panels start connected after a load?

**Comment by PrPleGoo** [comment]
Could try a spawn(5) on https://github.com/Persistent-SS13/Persistent-Bay/blob/dev/code/modules/power/solar.dm#L299

**Comment by ingles98** [comment]
Close this. This was probably saved_vars and i think it has been fixed long ago
