### ISSUE TITLE
Cleaner Grenades broken

### ISSUE THREAD

**Issue by Kurgis** [Persistent-SS13/Persistent-Bay#25]
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round

**Comment by SirBloodBuske** [comment]
Has to deal with saving

**Comment by XElectricX** [comment]
Yeah, same thing happened on Paradise. All grenades lose their contents during saving, so all grenades are duds.

**Comment by SirBloodBuske** [comment]
They still work if you take a screw driver to them after activating them

**Comment by XElectricX** [comment]
Yeah, did that by accident with a cleaner grenade 2 days ago. A surprise, but a welcome one.

**Comment by XElectricX** [comment]
I believe John fixed it, so this should be closed.
