### ISSUE TITLE
Various machines load with stock part settings on restart

### ISSUE THREAD

**Issue by ourpar** [Persistent-SS13/Persistent-Bay#256]
#### Description of issue
1) Whenever the server restarts, Autolathes, Protolathes, Circuit imprinters, and Exosuit fabricators function as if they have stock parts, even if it is fully upgraded. Using an empty RPED on the machine (as long as the machine itself has upgraded parts) will cause it to "reload" the buffs that the machine should have.

2) Autolathes also accept any materials now (wood, osmium, phoron, etc), maybe not a bug in itself but without the ability to remove the materials is definitely a bug (even deconstructing the machines causes it to disappear instead of spitting out like how metal & glass does)

#### Steps to reproduce 
1. Build a machine with upgraded parts
2. Save map & restart server
3. The machine now functions as if it has stock parts

#### Length of time in which bug has been known to occur
~~Probably since autolathes were revamped (https://github.com/Persistent-SS13/Persistent-Bay/pull/227 or https://github.com/Persistent-SS13/Persistent-Bay/pull/234 , it definitely wasn't an issue before)~~
I was wrong, I did some testing and I confirmed the autolathe (and all other machines mentioned) have had this problem since the server moved over to baycode.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: b5e191ef40279c1abd3f48e22780f8781e9f82ff - dev - 2018-06-03
Game ID: bUG-dIPl

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by PrPleGoo** [comment]
If you break the machine do you get tier 1 or 3 parts back?

**Comment by ourpar** [comment]
You'll get tier 3 parts, also I'm editing the bug report to better mention that this includes exosuit fab, circuit imprinter, and protolathe (probably all upgradable machines, but those are the ones I've confirmed personally)

Also, I made a mistake in the length of when the bug appeared, the bug has been around since forever but for some reason I thought the old style autolathes didn't have this issue, your PRs that I mentioned didn't break anything that was already broken before

**Comment by ourpar** [comment]
Tested it ingame, looks like https://github.com/Persistent-SS13/Persistent-Bay/pull/259 fixed it
