### ISSUE TITLE
[Low-Moderate] Various Wall Issues

### ISSUE THREAD

**Issue by UndeadNappist** [Persistent-SS13/Persistent-Bay#258]
* Description for incomplete walls and complete steel walls is reversed
* Spriting for "fusing" to adjacent walls waffles between functional and not, depending on which stage of completion the incomplete wall is at and what it's next to, leading to some hideous appearances (see picture of an assortment of old constructed steel walls and two incompleted walls)
![image](https://user-images.githubusercontent.com/7409796/40957523-749d8a1c-684a-11e8-95fd-b90a55e555a5.png)
* Girders take two steel to make, produce four - plating girders takes four steel, produces two to remove.
* Incomplete walls are functionally identical to complete ones, it just takes more steps to dismantle them. If you want to maximize time someone has to screw around with one you should just randomly leave it at a state of completion so they have to to try tools at random.

**Comment by Zero-Bits** [comment]
Spriting should be fixed by #278

**Comment by UndeadNappist** [comment]
It's not.

**Comment by UndeadNappist** [comment]
Walls are now fixed, although they tend to need "updating" by one step deconstruction and then full construction.
