### ISSUE TITLE
Reinforced tables are not showing proper sprites

### ISSUE THREAD

**Issue by ourpar** [Persistent-SS13/Persistent-Bay#267]
#### Description of issue
Whenever reinforcing a table with any material, instead of displaying the reinforced sprite, it shows the non-reinforced sprite of the used material. (ex: A glass table reinforced with gold will appear as a non-reinforced gold table).

#### Difference between expected and actual behavior
Expected: The reinforced sprite should appear after reinforcing a table

Actual: The non-reinforced sprite appears instead.

#### Steps to reproduce 
1. Build a table frame
2. apply any material to the frame to create a table
3.Use any material (drag click from hand to the table) to reinforce the table
4. Notice bugged sprite

#### Specific information for locating

Pretty much any material is affected, also the "table frame" item

#### Length of time in which bug has been known to occur
Unknown, if I had to guess it'd be since the walls update

#### Client version, Server revision & Game ID

Client Version: 511
Server Revision: 460af1d0fc324295d91d5a63302549597a3875d2 - dev - 2018-06-12
Game ID: bUQ-a7bz

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by ourpar** [comment]
Heres a picture of a marble table reinforced with steel: https://i.imgur.com/ZFvyzHO.png I'm posting this since you can actually see the marble table's sprite behind the steel table sprite, figured it could be helpful.

**Comment by PrPleGoo** [comment]
>Actual: The non-reinforced sprite appears instead.

Do you mean the sprite doesn't change or an unexpected sprite appears?

**Comment by ourpar** [comment]
An unexpected sprite appears, I'll try to explain it the best I can:
A non reinforced glass table will appear like [This](https://i.imgur.com/N9btaaG.png) (Which is intended)
However, when reinforcing the glass table with steel, it will appear like [This](https://i.imgur.com/XmMF30a.png) (the sprite of a non-reinforced steel table) when [it's supposed to appear like this](https://i.imgur.com/pbs1pbx.png)

**Comment by PrPleGoo** [comment]
https://github.com/Persistent-SS13/Persistent-Bay/blob/dev/code/modules/tables/tables.dm#L321
If someone could check these sprites.
I'm pretty sure this is where the issue originates.

**Comment by ingles98** [comment]
Fixed by #585
Finally closing this centuries old forgotten open Issue heh
