### ISSUE TITLE
Camera drones create a new camera entry on camera consoles on load

### ISSUE THREAD

**Issue by EyesNoEyes** [Persistent-SS13/Persistent-Bay#273]
#### Description of issue

https://i.imgur.com/ko1FLMi.png

#### Difference between expected and actual behavior

There should be only 1 camera drone entry to click on but there's like 20

#### Steps to reproduce 

Just look at the public camera console.

#### Length of time in which bug has been known to occur

Today.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [ ] Issue happened recently (less than 7 days ago)
- [ ] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Zero-Bits** [comment]
Does clicking any of the entries bring up the camera? Or is it only the latest that works?

**Comment by EyesNoEyes** [comment]
Yeah, any of the entries works.

**Comment by SirBloodBuske** [comment]
any update on this?
