### ISSUE TITLE
[Oversight] Rechargers cannot be made.

### ISSUE THREAD

**Issue by Kurgis** [Persistent-SS13/Persistent-Bay#284]
#### Description of issue
Rechargers cannot be created, meaning that energy weapons can never be recharged. Since nucguns have been removed, there's no energy weapon which can last more than a couple shots before expiring permanently.

#### Difference between expected and actual behavior

Create energy gun, use it, recharge with a recharger.

#### Steps to reproduce 

Attempt to recharge energy gun, realize there's no option to.

#### Specific information for locating

https://github.com/Persistent-SS13/Persistent-Bay/blob/dev/code/game/machinery/recharger.dm

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by PrPleGoo** [comment]
Wouldn't it make sense to just delete this machine and only allow cell charging?
