### ISSUE TITLE
Object options list bug or glitch I don't know

### ISSUE THREAD

**Issue by Infixx** [Persistent-SS13/Persistent-Bay#287]
#### Description of issue 
When you right click a object then go to to options such as you want to examine it, it instead comes up with a ton of options that are from the IC tab OOC tab etc and don't work and the standard object options are not available.

#### Difference between expected and actual behavior
When you right click a object then go to the options it's supposed to show the standard object options

#### Steps to reproduce 
Right click any object and then go to the options you will see a long list of stuff except the standard object options

#### Specific information for locating

Any object should work in showing the wrong options

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 466a411c4a489073c25a043feb39588f862e3a65 - dev - 2018-06-20
Game ID: bUY-cqpP

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by FaurnsGoldberg** [comment]
cannot reproduce

**Comment by ourpar** [comment]
Found this: http://www.byond.com/forum/?post=2378537

according to byond changelog it was fixed in the most recent beta patch

**Comment by Zero-Bits** [comment]
Righto. It looks like byond solved this one then.
