### ISSUE TITLE
Meson goggles allow you to see through walls even while turned off

### ISSUE THREAD

**Issue by ourpar** [Persistent-SS13/Persistent-Bay#301]
#### Description of issue
Meson goggles allow the wearer to see through walls while equipped, regardless if they are turned on or off.

#### Difference between expected and actual behavior
Expected: You should not be able to see through walls while turned off.
Actual: You can see through walls while turned off.

#### Steps to reproduce 
1.Equip/Obtain meson goggles
2. Make sure Meson goggles are turned off
3. Notice you can see through walls

#### Specific information for locating
Either Meson goggles itself or possibly wherever the overlay for meson goggles are stored

#### Length of time in which bug has been known to occur
Recent (?). The bug didn't always exist.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 7db9a2deec97de68e2377c0593f58d24a716c1de - dev - 2018-06-24
Game ID: bU2-dHFI

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by ourpar** [comment]
Some pictures of wearing the meson goggle in various states:
Mesons on (intended behavior): https://vgy.me/dBhszd.png 
Mesons off, no light source on character: https://vgy.me/WT1Z7o.png   
Mesons off, helmet light enabled: https://vgy.me/Gs994M.png

**Comment by ingles98** [comment]
Is this an issue ? I mean that could be a feature request instead of an issue, i might be wrong, but i think most other codebases don't have a toggle on just the meson goggles.
Maybe we add that
