### ISSUE TITLE
Deconstructing a wall and floor creates another wall

### ISSUE THREAD

**Issue by wixoaGit** [Persistent-SS13/Persistent-Bay#310]
Deconstructing a wall then the floor underneath it creates another wall.
Deconstructing this second wall and floor will also create a wall again.

![capture](https://user-images.githubusercontent.com/30789242/42139363-29491296-7d5a-11e8-8faf-367d18664fd6.PNG)

**Comment by UndeadNappist** [comment]
This only happens when you build a tile over asteroidspa tiles and then construct a wall on top of that.
Normal floors still interact fine, it's *just* mineable asteroid squares.

Hopefully this process won't occur again for any and all non-plating simulated floors.
