### ISSUE TITLE
Canisters no longer save properly

### ISSUE THREAD

**Issue by ourpar** [Persistent-SS13/Persistent-Bay#323]
#### Description of issue
Canisters do not save their pressure and (probably) gas contents after server restart.

#### Difference between expected and actual behavior
Expected: Canisters should save their gas mixture and pressure after restart
Actual: They default to 4559 kPa and to whatever mixture the canister is labeled (pure N2 canister always has pure N2 after restart)

#### Steps to reproduce 
1. Obtain a canister (I've only tested with N2 and O2 canisters)
2. Change pressure/mixture of gasses in canister to anything that isn't default.
3. Save + Restart server
4. Canister now has 4559 kPa (default pressure).

#### Specific information for locating

"Canister" (I assume all types are effected)

#### Length of time in which bug has been known to occur

Recently, I first noticed on July 1st

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 9a97dbdc3e4453b5d76c5856e2e22e619f3a7ebb - dev - 2018-07-02
Game ID: bU0-bjil

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by NataKilar** [comment]
This is fixed, and can be closed.
