### ISSUE TITLE
Character Creation: Starting Employer cannot be set, current -dev branch

### ISSUE THREAD

**Issue by badonkadong** [Persistent-SS13/Persistent-Bay#368]
#### Description of issue

Character Creation: Starting Employer cannot be set (Unset*)

#### Steps to reproduce 

Compile the code according to official instructions
Give yourself Host privileges
Start the server
Join
Try to create a character
Try to set an employer

#### Specific information for locating
no specific messages received.
By clicking on Finalize i get "You must choose a valid employer."
which cannot be chosen

#### Length of time in which bug has been known to occur
Every time.

#### Client version, Server revision & Game ID
Client Version: 512
Server Revision: Revision Unknown
Game ID: bVO-c26A

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by FaurnsGoldberg** [comment]
you'll need to spawn faction_spawner/nanotrasen and then spawn a frontier beacon and set its req_access_faction to "nanotrasen". The current build is under construction to a major degree, later builds will make it easier to run a new server with a fresh install
