### ISSUE TITLE
Icon Graphics [Low Priority]

### ISSUE THREAD

**Issue by UndeadNappist** [Persistent-SS13/Persistent-Bay#553]
When constructing reinforced walls from steel, one of the overlays unsuccessfully calls an image, resulting in a default error message for a sprite appearing as part of the wall.

![image](https://user-images.githubusercontent.com/7409796/45206361-ae2f1000-b239-11e8-97f2-7bb5002c1a4b.png)

Many sinks and other buildable plumbing do not properly adjust their pixels to shift and appear on the wall like air alarms.

Kitchen sinks are missing their north-facing icon.

**Comment by ingles98** [comment]
Andrew fixed this if im right on one of his icon update/hotfix
