### ISSUE TITLE
BUG: TABLE ICONS

### ISSUE THREAD

**Issue by SirBloodBuske** [Persistent-SS13/Persistent-Bay#574]
Wood Table Display the wrong icon.

**Comment by ingles98** [comment]
Same issue as #267 
I'll be sure to look into these in the next 2 days as I finish this project.

**Comment by PsyCommando** [comment]
Here's an image of the issue
![2018-09-13 13_29_42-persistence station 13 -](https://user-images.githubusercontent.com/8772299/45506602-bc12f280-b75d-11e8-967d-a3552b7d7ca2.png)

**Comment by ingles98** [comment]
#585 Fixes the issues. PM me if further instances of the same issue pop up on any other material.
