### ISSUE TITLE
BUG: CREW MANIFEST NULL

### ISSUE THREAD

**Issue by SirBloodBuske** [Persistent-SS13/Persistent-Bay#577]
![image](https://user-images.githubusercontent.com/11132143/45465739-166b6f00-b6dc-11e8-8b7e-a1b64da81979.png)

**Comment by ben10083** [comment]
https://imgur.com/PwqSQlD  Now it shows but ranks are not listed (shows only rank 1)

**Comment by SirBloodBuske** [comment]
Works untill you add more crew.
