### ISSUE TITLE
BUG: hemostat

### ISSUE THREAD

**Issue by SirBloodBuske** [Persistent-SS13/Persistent-Bay#578]
![image](https://user-images.githubusercontent.com/11132143/45466092-bf669980-b6dd-11e8-986c-5e4c74f767af.png)

**Comment by ingles98** [comment]
So the cooldown might be affected by the current mob Life() lag we're experiencing due to the latest lag issues. Once they're fix if this problem persists, leave a note.
Will remain open until further notice.
