### ISSUE TITLE
BUG: HELP I'VE FALLEN AND CAN'T GET BACK UP!

### ISSUE THREAD

**Issue by SirBloodBuske** [Persistent-SS13/Persistent-Bay#581]
Sometime you get knocked over, and literally will never get back up unless someone helps you.

**Comment by ourpar** [comment]
this is probably more to do with mob processing lagging rather than a bug itself, occasionally mob processing starts lagging and slows down things like metabolism, breathing, bleeding, simple mob actions, doors closing, and a bunch of other things I can't think of, not just the fall down stun

**Comment by ingles98** [comment]
Ill be checking if i can seperate the npcs from user mobs and setting npcs or offline users to lower priority queues that way. Will relieve the server load greatly.

**Comment by ingles98** [comment]
#583 
Should begin to fix the user mobs lag when it gets merged to Live.
