### ISSUE TITLE
SPRITE: hidden doors need to be resprited and orientation fixed

### ISSUE THREAD

**Issue by SirBloodBuske** [Persistent-SS13/Persistent-Bay#582]
![image](https://user-images.githubusercontent.com/11132143/45510610-5116eb00-b760-11e8-9623-4091e47aa9d9.png)

**Comment by ingles98** [comment]
Indeed. they discovered our secret phoron stash reeeee

**Comment by ingles98** [comment]
@Andrew-Fall did these got fixed by your icon update ?
