### ISSUE TITLE
Disappearing sprites.

### ISSUE THREAD

**Issue by JerryHellbound** [Persistent-SS13/Persistent-Bay#588]
#### Description of issue

Sprites of items disappearing. Such as produce. and leaving their space used up even though you can't get them out.
![capture](https://user-images.githubusercontent.com/25938351/45576399-3615ab00-b834-11e8-9744-d7e25c962020.PNG)

#### Difference between expected and actual behavior

Pretty sure its not supposed to happen.

#### Steps to reproduce 

Put something such as produce in a storage item such as a backpack or box and from my experience, simply cryo.

#### Specific information for locating

Got none.

#### Length of time in which bug has been known to occur

Pretty sure its been reported for quite a long time.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: aa6c7442d3d701e46721c7751276f69e8cb81ad1 - main - 2018-09-13
Game ID: bWl-cYG6

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by ingles98** [comment]
So it didn't happen right away ? You cryo'd and when you got back it happened ? Does it happen everytime you Cryo or between server restarts ?

**Comment by JerryHellbound** [comment]
> So it didn't happen right away ? You cryo'd and when you got back it happened ? Does it happen everytime you Cryo or between server restarts ?
> EDIT: What the hell is produce btw ?

When I'm playing it doesn't happen, after I cryo it happens everytime. In fact, it gets worse for those that didn't get completely deleted (I had a mushroom, it's stalk disappeared. Next time i'm awake, the entire thing disappeared.) Not only that, it seems like it also glitches the hell out of them, removing their contents, (A tomato makes an ermagdaz when put in a seed processor for example).
Every time I cryo.
Also, produce: "things that have been produced or grown, especially by farming."

**Comment by ingles98** [comment]
> Seems like it does that with genetically modified plants. I had modified potato in my smartfridge and they turned into a "fruit" entity with no sprite after server restart. Happened to a few other of my modified veggies too. The ones not genetically modified didn't seem affected.
> 
> Also, you got invisible "limb stump" items after someone explodes, or monkey corpses rot away/get exploded. Sometimes, jetpacks turns invisible. Seems to have to do with it changing state.

Thanks for your feedback on that. At least its very obvious now that it is a server saving issue.

**Comment by PsyCommando** [comment]
Well, limb stumps and jetpacks disapearing happened during gameplay. Produces changed after reload.
