### ISSUE TITLE
Ore Processor accepts no ores

### ISSUE THREAD

**Issue by ourpar** [Persistent-SS13/Persistent-Bay#594]
#### Description of issue
whenever dropping mined ores onto an input tile for the mineral processor, the machine does not pick up said ores, even if the machines are correctly configured.

#### Steps to reproduce 
1. Build processing station using the mineral processor, stacking machine, and ore processing console.
2. Sync the machines together by clicking on the ore processing console & setup input/output directions
3. Place ore on input tile
4. Realize ores are not being picked up

#### Specific information for locating

mineral processor

#### Length of time in which bug has been known to occur
Not too long ago, i'd assume whenever there was an attempted fix to made ore processors not eat items on characters. 

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: aa6c7442d3d701e46721c7751276f69e8cb81ad1 - main - 2018-09-13
Game ID: bWm-ci0r

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by ingles98** [comment]
The ore processor has always been working...

**Comment by ourpar** [comment]
I wouldn't make the issue if it didn't exist :v  
The stacking machine still works so I'm not just too stupid to set it up ingame. the server revision i posted (the one the server is on) also edited mineral_processor.dm (i think in attempt to fix it from eating items on mobs) so i'm fairly confident the mineral processor isn't not working

**Comment by ingles98** [comment]
You're probably pretty much very right, the changes to it didn't probably pass by the dev build. It is pretty much working on the dev, and i even just PR'ed a fix for the "lemme eat your shit" issue. I'll talk to Brawler

**Comment by ingles98** [comment]
#595 fixes this.
