### ISSUE TITLE
BUG: T-Comms Forever Off after start up

### ISSUE THREAD

**Issue by SirBloodBuske** [Persistent-SS13/Persistent-Bay#598]
![image](https://user-images.githubusercontent.com/11132143/45597456-68d5b580-b992-11e8-9403-2dcec287e1c0.png)
You have to rebuild each machine and relink everything.

**Comment by speeder** [comment]
more details: I tried to rebuilt a machine, and couldn't take out components, each time I hit it with a crowbar, a message would play I was removing a board, but nothing came out... and I could keep doing so forever, and seeing the message forever, and no component.

**Comment by SirBloodBuske** [comment]
Turns out were not cooling our stuff
