### ISSUE TITLE
BUG: filters and mixers disconnecting upon save/load

### ISSUE THREAD

**Issue by speeder** [Persistent-SS13/Persistent-Bay#602]
I saw in more than one station the following happen:

game save, loads, and then atmos room end overpressurized (or in one case, atmos room had literally zero pressure upon saving, and upon loading had exact same pressure as the pipes inside it that suffered this bug).

When I went to check, noticed the sprite of the pipes that are going into filters and mixers change to the sprite when you just put down a new pipe, with the "u" shaped end, even if touching a square-shaped end on the filter/mixer.

Removing, and putting them back, fix the issue.

I saw this happen whenever a "device" was connected straight into a filter/mixer, like pump and valve, and seemly (I am not sure the pipe really disconencted or was sprite bug) this happened a couple times on NT station between the filters and the fuel pipes that go into the tanks.

**Comment by PsyCommando** [comment]
Seems to be only for mirrored variants. I pushed a PR which might fix this.
#811
