### ISSUE TITLE
Floor lights are in a weird limbo state on map load

### ISSUE THREAD

**Issue by PsyCommando** [Persistent-SS13/Persistent-Bay#609]
#### Description of issue
When the server loads from a save, all floor lights placed down and turned on will load in the On state, but visually and mechanically will be off. Aka, the sprite doesn't light up, and the area around them isn't lit up either. So you have to turn them off and on again manually.

#### Difference between expected and actual behavior
Floor lights that were turned "on", on server save, should be truly on and working on server load.

#### Steps to reproduce 
Place down floor lights. Save, then restart server. Lights will be stuck on, but not emitting light or displaying their "ON" sprite.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 65e5b165ee3d1bb836fb1bb1b044872fce1a75a9 - main - 2018-09-16
Game ID: bWn-cYfS

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by ingles98** [comment]
Some vars should be saved for the light level itself and possibly the icon state
