### ISSUE TITLE
BUG: Things disappearing to 1,1,1

### ISSUE THREAD

**Issue by SirBloodBuske** [Persistent-SS13/Persistent-Bay#621]
We have noticed things going here, as even some players were transported there today. 

![image](https://user-images.githubusercontent.com/11132143/45603100-322d8880-b9ee-11e8-9b37-f5c7d7b0686d.png)

**Comment by SirBloodBuske** [comment]
![image](https://user-images.githubusercontent.com/11132143/45603176-fd6e0100-b9ee-11e8-8f64-60e4ea3099c4.png)

**Comment by ingles98** [comment]
Nullspace spotted hehe

**Comment by ingles98** [comment]
Was this a one time isolated event?

**Comment by ingles98** [comment]
Objects and mobs will move here if something went wrong while loading their locs. These incidents might not be related at all when they happen
