### ISSUE TITLE
SUGGESTION: Allow Factions to kick Telepads off the network.

### ISSUE THREAD

**Issue by SirBloodBuske** [Persistent-SS13/Persistent-Bay#634]
Or maybe add a permissions so only said person with said access can allow the telepad, or both.

**Comment by SirBloodBuske** [comment]
https://github.com/Persistent-SS13/Persistent-Bay/commit/1d4ffed2cb40dffffea053c354c423a28f92ae6e

**Comment by ingles98** [comment]
@SirBloodBuske i cant seem to find nothint on the PR that changes anything related to the issue

**Comment by SirBloodBuske** [comment]
Sorry I linked the wrong pr

**Comment by SirBloodBuske** [comment]
https://github.com/Persistent-SS13/Persistent-Bay/commit/2907ee4fe54b8cbcef12ff36be37bf0d9b91a2cc
