### ISSUE TITLE
SUGGESTION: Remove All Access from Cleaning Bots

### ISSUE THREAD

**Issue by SirBloodBuske** [Persistent-SS13/Persistent-Bay#635]
They will vent your station. And get abused.

**Comment by ingles98** [comment]
Holy shit i didnt realize. Will see it when i get home

**Comment by PsyCommando** [comment]
Well, public airlocks are still a thing. So maybe throwing in a check to make sure not to open a door leading to a vacuum turf from a air containing turf be a good idea too.
