### ISSUE TITLE
BUG: Sleepers eject their content

### ISSUE THREAD

**Issue by SirBloodBuske** [Persistent-SS13/Persistent-Bay#636]
Including their boards and parts.

**Comment by ingles98** [comment]
Interesting ill give a look

**Comment by ingles98** [comment]
Reference this issue on the PR you make when you fix it.

**Comment by SirBloodBuske** [comment]
Fixed as per https://github.com/Persistent-SS13/Persistent-Bay/commit/1d4ffed2cb40dffffea053c354c423a28f92ae6e
