### ISSUE TITLE
BUG: gas being duped

### ISSUE THREAD

**Issue by speeder** [Persistent-SS13/Persistent-Bay#640]
I have no clue how to reproduce it... If I knew would been much easier for me to debug this myself.

But long story short: several stations in the game have unexplained pressure some time after reboot.

Example: there was one station with no atmos, that were filled exclusively with canisters until air was barely breathable to save money, resulting in 82kpa...

After a reboot on next day, air was 247kpa, and no matter how many times I used air pumps to drain air in a certain room, it would stick around that number if I left room alone too long.

After another reboot, pressure managed to spike to 2000kpa, meanwhile no canisters were bought.

Another example:

There is one station I built some simple atmos, left everything at 101kpa
Next day when I entered station, all alarms were green, but as soon I opened the entrance door, whole station became red alarm at same time, and pressure spiked to 240kpa

When I opened door to atmos room, pressure there was rising for no reason, as if something was continuously outputting gas, at some point it reached 970kpa

Situation stabilized after I removed all pipes I could find with wrench, and put them back, literally, then I vented station until it was 101kpa again...

In the next day I didn't played, but other players reported seeing this station with 10.000kpa in all rooms...

NT example:

upper deck often get overpressurized for no obvious reason, usually up to around 200kpa before someone syphons it... also nitrogen tank need to be vented often, it tends to fill and freeze the waste loop, even when noone is buying any canisters, it is not unusal to see pipes between nitrogen filter and nitrogen tank with pressure of 30000kpa

**Comment by ingles98** [comment]
Oh boi.

**Comment by ingles98** [comment]
Weird thing is that those readings dont match anything ive seen before. I can try several save and reboots to see if any dupplication or increment on the air contents, and ill do so today. Are you building anything peculiar on those rooms compared to NTs? I dont think i ever seen someone talking about too much kPa on a whole roo. After a while

**Comment by ingles98** [comment]
Also, have you left any open canister or noticed it might got duped its contents?

**Comment by speeder** [comment]
canister MIGHT be doing it...

But I saw it happen in rooms with no canisters too.

One particular room seemly was fixed the issue (I am not sure if that was it) was removing a makeshift pressure sensor someone built:

it was 1 "injector", attached to 1 pipe, with a "meter" on top of pipe.

Eyes suggested that this might been the cause of the dupe, with the save/load process causing the open pipe to collect the room air, repopulate things, then spawn it back, duping it. Anyway, unwrenching the open pipe+injector made the room stop overpressurizing so often.

**Comment by speeder** [comment]
My suspicion, is the error is in the lines I will paste below. I don't did investigation of it myself because I can't figure how to make the local server work for testing...

lines 135 and 137 of code/modules/atmospherics/datum_pipeline.dm

`turf_copy.subtract(target.zone.air)

target.zone.air.merge(turf_copy)`
