### ISSUE TITLE
Ejecting cryogenic store pods dispenses their intercom, board and stock parts

### ISSUE THREAD

**Issue by factoryman942** [Persistent-SS13/Persistent-Bay#68]
#### Difference between expected and actual behavior
The pod should likely only be dispensing any equipment within it, and not the actual pod's parts
#### Steps to reproduce 
Right-click cryogenic freezer
Select "Eject Pod"

#### Client version, Server revision & Game ID
Client Version: 512
Server Revision: 0f0150acd6d78c9c7b6e298155e52544eab484a6 - dev - 2018-03-26
Game ID: bTz-dibG

**Comment by FaurnsGoldberg** [comment]
fixed
