### ISSUE TITLE
Pizza took my knife

### ISSUE THREAD

**Issue by pantherpusher** [Persistent-SS13/Persistent-Bay#72]
#### Description of issue
Pizza stole my knife

#### Difference between expected and actual behavior
I expected the knife to cut the pizza but it instead slipped the knife into the pizza

#### Steps to reproduce 
Take an osmium-carbide plasteel butterfly knife and click a pizza with it

#### Specific information for locating

Margherita Pizza
osmium-carbide plasteel butterfly knife

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by XElectricX** [comment]
Wait, what.

I'll uuuh try to reproduce it.

**Comment by Zero-Bits** [comment]
The knife has to be opened for it to cut.

**Comment by matt81093** [comment]
Either not a bug, or a message could be printed saying you can't cut the pizza while the knife isn't out, with maybe a popout asking if you want to insert this item into the pizza. *shrugs*

**Comment by rhicora** [comment]
This has to be the most ss13 bug ever.

**Comment by UndeadNappist** [comment]
Same thing happens when you use a tactical knife on the pizza. Slips it in without cutting it.

**Comment by Zero-Bits** [comment]
It is a feature, but it's a feature that conflicts with another feature.

**Comment by Zero-Bits** [comment]
Solved by #242
