### ISSUE TITLE
When you look  at crew manifest in the lobby, it shows all members as "unset" 

### ISSUE THREAD

**Issue by Spankmonkey777** [Persistent-SS13/Persistent-Bay#73]
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Zero-Bits** [comment]
I'll probably just rework the crew manifest to only show active players of your faction. I'll see if I can't fix this while I'm at it, although, IIRC it's because the crew records aren't being updated with the IDs.

**Comment by FaurnsGoldberg** [comment]
this got fixed by zerobits
