### ISSUE TITLE
Food loses the recolorable portion of its sprite on cryo or server restart

### ISSUE THREAD

**Issue by Draxtheros** [Persistent-SS13/Persistent-Bay#740]
#### Description of issue
The recolorable portion of food (the filled portion of bread, the flecks on pancakes, the chunks on kabobs, the entirety of baked meat) dissapears when you are removed from the game or the server restarts. This can result in some food items becoming stuck in your inventory due to no sprite to interact with.

Edit: It seems in general items that are assigned a color at creation lose their color at server restart. This includes things like bags of Unathi blood bags(normally a pinkish orange color) turning red like normal blood bag.

#### Difference between expected and actual behavior
Food isn't supposed to be invisible.

#### Steps to reproduce 
Step 1: Bake meat
Step 2: Cryo
Step 3: Bug the meat gods to remove the meat from your inventory as it is now a bluespace anomaly taking up your inventory space.

#### Specific information for locating
Any food item with a portion of its sprite that is recolored based on whatever ingredients are inside it.

#### Length of time in which bug has been known to occur
At least a week and a half before today, 9/27/2018

#### Client version, Server revision & Game ID
Client Version: 512 (no further information is being given by the command)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Kurgis** [comment]
Issue is present for me as well, certain food items vanish in inventory. Food items, such as fruit slices, become invisible and unusable on restart.
