### ISSUE TITLE
RCD Matter tank content isn't saved

### ISSUE THREAD

**Issue by PsyCommando** [Persistent-SS13/Persistent-Bay#747]
#### Description of issue
When you place a matter bin in a RCD and the server saves it like that. When it'll reload the save the RCD will be empty.

#### Difference between expected and actual behavior
The RCD should save and reload properly its matter content.

#### Steps to reproduce 
Load RCD with matter, save server, restart server.

#### Length of time in which bug has been known to occur

At least a week.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 35abeb74e0ac7e2a85ab0dd64cd7a2430710273f - main - 2018-09-28
Game ID: bWz-aUvX

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Draxtheros** [comment]
This issue extends to several other kinds of machines. The Pathogenic Isolator will forget any syringes left in the tray, while retaining its loaded sprite. Similarly the Pathogenic Incubator loses all stored virus food and possibly even loaded beakers.
