### ISSUE TITLE
Air alarms, vents and scrubbers behave inconsistently

### ISSUE THREAD

**Issue by PsyCommando** [Persistent-SS13/Persistent-Bay#760]
#### Description of issue
It seems air alarms tend to lose track of their scrubbers and vents over time. Some of them randomly turn on/off while all the others are on and fine. Also sometimes individual scrubbers/vent turn to siphon or any other modes while the air alarm is set to filter for example. And its clearly not due to griefing. And it happens constantly.

My hypothesis, and I think others might agree is that the radio system that links air alarms and vents/scrubbers is very likely to end up mixing vents/scrubbers ids and frequencies because it doesn't refer to individual vents/scrubber via a unique ID like a GUID internally.
So, maybe allowing air alarms to only broadcast commands to vents/scrubbers in the same area might be a solution?

#### Difference between expected and actual behavior
Vents and scrubbers should be in the state that the air alarms assigned to them commands, and keep that state until changed by the air alarms in the same area. Instead, their state will sometimes change randomly during gameplay.

#### Steps to reproduce 
Make lots of areas on several Z levels each with atmos and (air alarm + vents + scrubbers) and change some area alarms to siphon and then compare all other area scrubbers/vents to their previous states.

#### Length of time in which bug has been known to occur

More than a week.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 35abeb7 - main - 2018-09-28
Game ID: bWz-aUvX

And later revisions. (Server is down currently)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by PsyCommando** [comment]
Looking into it a bit more, the air alarm code is kind of a mess..
It changes the auto assigned vent/scrubber name remotely, when that's done already in the vents/scrubbers themselves.
```
/obj/machinery/alarm/proc/register_env_machine(var/m_id, var/device_type)
	var/new_name
	if (device_type=="AVP")
		new_name = "[alarm_area.name] Vent Pump #[alarm_area.air_vent_names.len+1]"
		alarm_area.air_vent_names[m_id] = new_name
	else if (device_type=="AScr")
		new_name = "[alarm_area.name] Air Scrubber #[alarm_area.air_scrub_names.len+1]"
		alarm_area.air_scrub_names[m_id] = new_name
	else
		return
	spawn (10)
		send_signal(m_id, list("init" = new_name) )
```

It constantly seeks a new "master" air alarm each times it receive a signal, 
```
/obj/machinery/alarm/receive_signal(datum/signal/signal)
	if(stat & (NOPOWER|BROKEN))
		return
	if (alarm_area.master_air_alarm != src)
		if (master_is_operating())
			return
		elect_master()
		if (alarm_area.master_air_alarm != src)
			return
	if(!signal || signal.encryption)
		return
	var/id_tag = signal.data["tag"]
	if (!id_tag)
		return
	if (signal.data["area"] != area_uid)
		return
	if (signal.data["sigtype"] != "status")
		return

	var/dev_type = signal.data["device"]
	if(!(id_tag in alarm_area.air_scrub_names) && !(id_tag in alarm_area.air_vent_names))
		register_env_machine(id_tag, dev_type)
	if(dev_type == "AScr")
		alarm_area.air_scrub_info[id_tag] = signal.data
	else if(dev_type == "AVP")
		alarm_area.air_vent_info[id_tag] = signal.data
```

And this just doesn't feel right. Changing the individual air alarms's mode variable directly, manually, in the same area while also directly ordering the area's vents and scrubbers to change state. I feel like this is bound to cause problems here..
```
/obj/machinery/alarm/proc/apply_mode()
	//propagate mode to other air alarms in the area
	//TODO: make it so that players can choose between applying the new mode to the room they are in (related area) vs the entire alarm area
	for (var/obj/machinery/alarm/AA in alarm_area)
		AA.mode = mode

	switch(mode)
		if(AALARM_MODE_SCRUBBING)
			for(var/device_id in alarm_area.air_scrub_names)
				send_signal(device_id, list("power"= 1, "co2_scrub"= 1, "scrubbing"= 1, "panic_siphon"= 0) )
			for(var/device_id in alarm_area.air_vent_names)
				send_signal(device_id, list("power"= 1, "checks"= "default", "set_external_pressure"= "default") )

		if(AALARM_MODE_PANIC, AALARM_MODE_CYCLE)
			for(var/device_id in alarm_area.air_scrub_names)
				send_signal(device_id, list("power"= 1, "panic_siphon"= 1) )
			for(var/device_id in alarm_area.air_vent_names)
				send_signal(device_id, list("power"= 0) )

		if(AALARM_MODE_REPLACEMENT)
			for(var/device_id in alarm_area.air_scrub_names)
				send_signal(device_id, list("power"= 1, "panic_siphon"= 1) )
			for(var/device_id in alarm_area.air_vent_names)
				send_signal(device_id, list("power"= 1, "checks"= "default", "set_external_pressure"= "default") )

		if(AALARM_MODE_FILL)
			for(var/device_id in alarm_area.air_scrub_names)
				send_signal(device_id, list("power"= 0) )
			for(var/device_id in alarm_area.air_vent_names)
				send_signal(device_id, list("power"= 1, "checks"= "default", "set_external_pressure"= "default") )

		if(AALARM_MODE_OFF)
			for(var/device_id in alarm_area.air_scrub_names)
				send_signal(device_id, list("power"= 0) )
			for(var/device_id in alarm_area.air_vent_names)
				send_signal(device_id, list("power"= 0) )
```

**Comment by ingles98** [comment]
Yeah i kinda seen this strange behaviour happening. Look into how they save and load their uids. Also if it is not already set, the air alarm should only check for area vents and scrubbers but i believe it also uses zones as it is able to have multiple air alarms on the same area, at least on tg, i could be wrong on this codebase.

**Comment by PsyCommando** [comment]
Okay, I found some place where I can reproduce the issue consistently. On the Cythos base, there's a vent plugged into a cooler and a small pipe section to cool ambient air in Tcomms. It should be set to siphon normal, and internal pressure checks. But when I change  it to siphon, there's another vent around the docks that just seems to change to siphon too..

Their name don't match "Server Room Vent Pump #2", and the other one tied to it is "Central Hallway Vent Pump #3". So they most likely have different areas.. But looking at the code, vents for each areas are stored in a list in the areas themselves.. So I'm a bit kinda stumped here.. 

And well, the multiple air alarms in the same areas feature on our codebase is kind of half-assed. It just elects a "master" air alarm on occasions.. Like whenever it receives a broadcast from the vents/scrubbers it checks and elects a master alarm. Which sounds a bit of a glitch prone way of doing that. I get the feeling the alarms probably fight eachothers a lot..

**Comment by ingles98** [comment]
I will look into changing that behaviour. I will keep the air alarms not unique and try ro circunvent around that
