### ISSUE TITLE
Items can be rotated when multiple tiles away

### ISSUE THREAD

**Issue by ourpar** [Persistent-SS13/Persistent-Bay#774]
#### Description of issue
Items can be rotated by ALT + LMB click when your character more than one tile away

#### Difference between expected and actual behavior
You should only be able to rotate when standing next to the item.

#### Steps to reproduce 
1. find an item that can be rotated ( glass panes, mining braces, etc.)
2. Alt + Left click while more than one tile away
3. discover you have telekinesis.

#### Length of time in which bug has been known to occur

If I were to guess, the PR that added [ALT clicking](https://github.com/Persistent-SS13/Persistent-Bay/pull/641) is when it started (rip buske)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by ingles98** [comment]
Hehe yes, i saw what was the cause right when I read the title. It is missing the distance check. Ill let newcommers work on that.

**Comment by AlAtEX** [comment]
Shouldn't this issue be closed?

**Comment by ourpar** [comment]
yep, thanks for the reminder.
