### ISSUE TITLE
You can bypass the blueprint room size limit by merging areas together 

### ISSUE THREAD

**Issue by ourpar** [Persistent-SS13/Persistent-Bay#775]
#### Description of issue
You can bypass the blueprint room size limit by merging two areas together 

#### Difference between expected and actual behavior
If you can't create an area past a certain size, it seems like you shouldn't be able to merge two areas together to bypass the size restriction

#### Steps to reproduce 
1. Create an area under the size limit
2. Create a second area under the size limit
3. Merge the two areas together to bypass the size limit

#### Specific information for locating

blueprints (I guess?)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by ingles98** [comment]
Thanks for the feedback on that. Ill set this to good first issue for the simple check but if not looked into in time ill do it myself.

**Comment by PsyCommando** [comment]
But, how is that a problem? The room size limit was adjusted recently because some people tried to map space accidentally. The merging of rooms is currently the only way to make average length hallways.

**Comment by ingles98** [comment]
> But, how is that a problem? The room size limit was adjusted recently because some people tried to map space accidentally. The merging of rooms is currently the only way to make average length hallways.

Thats seems right. We will see what @FaurnsGoldberg has to say on this.
