### ISSUE TITLE
Integrated Circuits Don't Save/Load Properly

### ISSUE THREAD

**Issue by WolfWarez** [Persistent-SS13/Persistent-Bay#776]
#### Description of issue
Integrated circuit designs that have been left on the floor will lose all of their internal components upon the server saving/loading. 

#### Difference between expected and actual behavior
It would be expected that the devices would have their components saved and variable saved, and would continue their previous behavior on save/load. Currently, after save/load, they become empty assemblies, with only their name saved.

#### Steps to reproduce 
Create an assembly of any complexity, as even a simple light circuit lost its components.
Leave it on the floor, as ones within player inventories, at least going to and from cryo, seem unaffected.
Wait for a save/load.

#### Specific information for locating

integrated circuit printer

#### Length of time in which bug has been known to occur

I'm not sure. I just woke up from cryo to find every assembly in its place, without its parts.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: ef7de3b2db8cd6d7b1982ba73d7dc35d0726f9e4 - main - 2018-10-01
Game ID: bWD-bpGz

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced after a restart
- [X] Issue happened recently (less than 7 days ago)
- [X] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by ingles98** [comment]
Known issue. It wont be looked into soon as it is yet to be reworked.
