### ISSUE TITLE
Coffee is dangerous

### ISSUE THREAD

**Issue by PsyCommando** [Persistent-SS13/Persistent-Bay#779]
#### Description of issue
Seems like around 2 cups of coffee will kill you. Which is worst than any other alcohol. And well, it could be used as a weapons.

#### Difference between expected and actual behavior
Drinking coffee shouldn't kill you after 2 cups..

#### Steps to reproduce 
Drink 2 cups of coffee.

#### Length of time in which bug has been known to occur

Apparently a while.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: ef7de3b2db8cd6d7b1982ba73d7dc35d0726f9e4 - main - 2018-10-01
Game ID: bWD-bpGz

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by ingles98** [comment]
Looking into it i found out it is indeed poisonous to tajaran. Shouldnt be for humans.
Ill have to check how much is needed to overdose. Since coffee is supposed to be watered already, it shouldnt hurt as if it is very concentrated caffeine. Until then i advise mixing water

**Comment by PsyCommando** [comment]
Well, we've had an engineer die to it yesterday. He said he drank 2 cups. Now he's in a LMI..

**Comment by ingles98** [comment]
Alright somewhere the coffee turns into adrenaline reagent and thats where we fix it. Maybe we devide it x times appropriately. Ill give a look

**Comment by JerryHellbound** [comment]
I tried to see if I could recreate this problem by having a carbon human drink 2 cups exactly of coffee from a dispenser that was prefilled. After around 40 mins they still haven't gotten any heart problems.

**Comment by PsyCommando** [comment]
hmm.. what about double? There might be something else factoring in too then..
