### ISSUE TITLE
Clocking out of businesses on Lace UI does not work

### ISSUE THREAD

**Issue by ourpar** [Persistent-SS13/Persistent-Bay#781]
#### Description of issue
When accessing the lace UI while clocked into a business network, the "Clock out" button appears to do nothing when pressed.

#### Steps to reproduce 
1. Clock into a business from a modular computer
2. Access Lace UI and attempt to clock out
3. Realize you can't clock out from your lace

#### Length of time in which bug has been known to occur

Quite a while

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: ef7de3b2db8cd6d7b1982ba73d7dc35d0726f9e4 - main - 2018-10-01
Game ID: bWD-bpGz

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by PsyCommando** [comment]
Can confirm that. You need to do it in the business app for it to work right now.
