### ISSUE TITLE
Door have no air on reload

### ISSUE THREAD

**Issue by PsyCommando** [Persistent-SS13/Persistent-Bay#794]
#### Description of issue
Doors have not air on reload and it causes issues when you walk through them. After going a few doors on reload, you'll get bruises everywhere.

#### Difference between expected and actual behavior
Doors should store the air on their turf on save.

#### Steps to reproduce 
Save, open several doors, stay in the doorway a bit and you'll see the pressure warning and O2 warning.

#### Length of time in which bug has been known to occur

More than a week.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 2d509af01147042e446e12d1be9afe74e0cf17e7 - main - 2018-10-04
Game ID: bWF-bhTU

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by ingles98** [comment]
One sad issue that i havent been able to tackle from the many atmos issues we currently have. The issue is not entirely replicable
