### ISSUE TITLE
Can't put label on large boxes

### ISSUE THREAD

**Issue by PsyCommando** [Persistent-SS13/Persistent-Bay#797]
#### Description of issue
Tagging a large box with the labeller does nothing. The labeller is just placed inside the box. And that's in either modes.

#### Difference between expected and actual behavior
Labeller should label large boxes and only be put inside when not labelling/removing a label.

#### Steps to reproduce 
Use labeller on large box.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 2d509af01147042e446e12d1be9afe74e0cf17e7 - main - 2018-10-04
Game ID: bWF-bhTU

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by ourpar** [comment]
same with backpacks, and any other storage container that can fit libelers it seems. (a workaround is filling the container until it's full, then attempting to label will work)
