### ISSUE TITLE
Light amplifications google in the tactical armor kit don't turn off properly

### ISSUE THREAD

**Issue by PsyCommando** [Persistent-SS13/Persistent-Bay#798]
#### Description of issue
Turning off the tactical light amplification googles makes everything but the character turn black.

#### Difference between expected and actual behavior
Your vision should return to normal after turning them off.

#### Steps to reproduce 
Wear the googles, and turn them off.

#### Length of time in which bug has been known to occur

At least one day

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 2d509af01147042e446e12d1be9afe74e0cf17e7 - main - 2018-10-04
Game ID: bWF-bhTU

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by ourpar** [comment]
seems to be the same bug as https://github.com/Persistent-SS13/Persistent-Bay/issues/580 , just with different goggles
