### ISSUE TITLE
Sugestion create a public market.

### ISSUE THREAD

**Issue by JulianCarlosShirey** [Persistent-SS13/Persistent-Bay#812]
#### Description of issue

We have no way to actually exchange good on the map using the telepads.

#### Description of the sugestion

Make a public market that will allow player to make request for goods on the server.
Those request could be fill using the same system as the current export system.

#### First step will be to collect request

Something like the Warrant Assistant program where it's simply a public listing of some text.
Swipe card to apply your name as the buyer's representative, and your faction or business as the purchasing entity.
Also a text field for a description of what you're buying, and a number field for the price you are bidding.

####  Step by step implementation

- [ ] First step is to make public place where to put orders like detailed above.
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by JulianCarlosShirey** [comment]
Nappist say:

Calling a specific shuttle for bills of sale and purchase would work better as it's also the first steps towards building a trade system involving shuttles.
Instead of necessarily revealing what z-level you're on, you could list a specific shuttle that will be at x address at a given time
Which would allow a greater depth of "public" trading hubs and "private" manufacturing/productive hubs

**Comment by PsyCommando** [comment]
Maybe a Frontier Ebay kind of App for computers could be interesting?

**Comment by ingles98** [comment]
Dunno what is best for players:
 - A computer app that you can use to sell stuff by comitting them to a telepad, going to 'nullspace' until its retrieved.
 - Or let players build trade systems themselves

**Comment by Pandolphina** [comment]
Suggestion here.

Let factions/players make their own imports. Basically, you can make a crate that has a set amount of items (that you must obtain and put into it) and a price that you choose.

Maybe even make a machine that you can set to print autolathe items in bulk, kinda like how you can do with the protolathe.
