### ISSUE TITLE
UI for valves/valves are disabled on reboot

### ISSUE THREAD

**Issue by UndeadNappist** [Persistent-SS13/Persistent-Bay#824]
#### Description of issue
The user interface for pressure regulators is disabled on server reboot if they are on a space square.
Furthermore, much of the time pipes themselves will cease allowing gas to flow through.

#### Steps to reproduce 
Have any kind of atmopsherics plumbing into a room that people do not enter or interact with / have a pipe in a space tile.

#### Length of time in which bug has been known to occur
A few months.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced after a restart
- [X] Issue happened recently (less than 7 days ago)
- [X] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by PsyCommando** [comment]
Manual valves and digital ones don't have UI though? Unless you mean pressure regulators?

**Comment by UndeadNappist** [comment]
I meant pressure regulators. Edited.

**Comment by PsyCommando** [comment]
This should fix it #831 Let me know when its merged if it works for you
