### ISSUE TITLE
Unintended Floor tiles to steel walls. Girder dupe.

### ISSUE THREAD

**Issue by HbsRed** [Persistent-SS13/Persistent-Bay#847]
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Tetsukiba** [comment]
Rods also work in the same fashion
