### ISSUE TITLE
Can't fill up air tanks using canister

### ISSUE THREAD

**Issue by PsyCommando** [Persistent-SS13/Persistent-Bay#884]
#### Description of issue
Can't fill your air tanks at a canister. It just sprays puddles around and doesn't actually fill the puddle.

#### Difference between expected and actual behavior
It should fill the air tank.

#### Steps to reproduce 
Put air tank in canister, turn valve open.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: e9a2816e5a2bdb88d9073d00a2ff47d409356218 - main - 2018-10-14
Game ID: bWP-c6f7

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by ourpar** [comment]
can confirm, i tried refilling an empty jetpack with nitrogen (at  20ｰC / 293K), the content just spilled on the floor instead of refilling my empty tank, and shortly evaporated.

**Comment by JulianCarlosShirey** [comment]
oxygen tank are working las time i check.

**Comment by ourpar** [comment]
since SOM was reverted this bug is pretty much fixed, yeah
