### ISSUE TITLE
radioless airlock controller

### ISSUE THREAD

**Issue by ourpar** [Persistent-SS13/Persistent-Bay#885]
#### Description of issue
1. the "Airlock Controller" wall mount does not anchor to the wall, as in I am able to drag after placing it on the wall
2. not exactly a bug, but I feel it's more of an oversight: The Airlock controller starts with safety on by default, meaning you have to set it up completely to access the UI to deconstruct it (which would be frustrating if you placed it in a bad location)

#### Steps to reproduce 
For 1:
Place airlock controller on a wall
CTRL + LMB to start dragging it around
For 2:
Place airlock controller on a wall
attempt to access UI to turn off safety
>Error: Missing device (exterior airlock, interior airlock, air vent, scrubber, interior sensor) 

be sad when you can't deconstruct

#### Specific information for locating

"Airlock Controller"

#### Length of time in which bug has been known to occur

since today

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: e9a2816e5a2bdb88d9073d00a2ff47d409356218 - main - 2018-10-14
Game ID: bWP-c6f7

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by ourpar** [comment]
another bug that seems to be consistent after multiple attempts at linking is only one vent activates when refilling/fast siphoning air, even if two are linked

**Comment by ingles98** [comment]
Oh shit i didnt see this!

Yes i see the problem
Now about the multiple vents, only two vents are able to be added atm, dunno what is going on with that second one tho.

Will look further into this afterwards, as it is possible we won't need norad controllers no more in Nexus, maybe.
