### ISSUE TITLE
Free Air Tanks

### ISSUE THREAD

**Issue by tinfoiltophat** [Persistent-SS13/Persistent-Bay#940]
#### Description of issue
When building air tanks with the autolathe, they do not require resources.

#### Difference between expected and actual behavior
One would expect air tanks to have some sort of cost in metal, but they do not.

#### Steps to reproduce 
1. Open autolathe menu.
2. Scroll to Air Tank
3. Build to your heart's content.

#### Specific information for locating

says No Resources Required next to the entry on the lathe

#### Length of time in which bug has been known to occur

N/A

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: b485ef2cf9b8dcd5e1cfabb1c915e1e412cf467f - main - 2018-10-21
Game ID: bWW-cF4B

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by astralenigma** [comment]
Weird, it should auto-close when the commit is made.
