### ISSUE TITLE
Streamlined medical suit is still spawns "/prepared" in cargo

### ISSUE THREAD

**Issue by ourpar** [Persistent-SS13/Persistent-Bay#947]
#### Description of issue
Streamlined/heavy duty medical voidsuit still spawns as `/obj/item/clothing/suit/space/void/medical/alt/prepared` 

#### Difference between expected and actual behavior
Due to the bugs with /prepared it should spawn as
`/obj/item/clothing/suit/space/void/medical/alt`
with magboots and helmet being completely separate item contents in the cargo crate.

#### Steps to reproduce 
1. order streamlined suit
2. import streamlined suit
3. obtain a /prepared suit AND separate helmet and magboot (so 1 suit, 2 magboots, and and 2 helmets are technically in the current import)

#### Specific information for locating

cargo imports -> medical tab -> "EVA - Heavy-duty medical voidsuit" import

**Comment by Pandolphina** [comment]
Will fix in about 6-8 hours.
