### ISSUE TITLE
I can't build an head for the mech named Ripley

### ISSUE THREAD

**Issue by JulianCarlosShirey** [Persistent-SS13/Persistent-Bay#948]
Their is also no possibibilite to build a firefighter mech

**Comment by ourpar** [comment]
a head is not needed to build ripleys (or any other mechs)

more info on the firefighter mech would be helpful

**Comment by Pandolphina** [comment]
Create a Firefighter APLU chassis using the exosuit fabricator. It is listed under exosuit equipment.
Create all parts of the Ripley APLU except for the chassis.
Assemble all of the Ripley parts to the Firefighter chassis.
Add a firesuit
Wrench
Screwdriver
Cable Coil
Wirecutters
Ripley central control
Screwdriver
Ripley peripherals control
Screwdriver
5 pieces of plasteel
Wrench
Weldingtool
5 pieces of plasteel
5 pieces of plasteel
Wrench
Weldingtool

**Comment by Pandolphina** [comment]
Issue fixed, please close.
